on:
  push:
    branches:
      - master

jobs:
  build-and-push:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install AWS CLI
        run: |
          curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
          unzip awscliv2.zip
          sudo ./aws/install

      - name: Install AWS Lightsail plugin
        run: curl "https://s3.us-west-2.amazonaws.com/lightsailctl/latest/linux-amd64/lightsailctl" -o "/usr/local/bin/lightsailctl"

      - name: Make plugin executable
        run: sudo chmod +x /usr/local/bin/lightsailctl

      - name: Build Docker image
        run: docker build -t cf-deploy:latest .

      - name: Login to AWS and push to Lightsail
        run: aws lightsail push-container-image --region us-east-2 --service-name container-service-1 --label cf-deploy-2 --image cf-deploy:latest
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
